### ISSUE TITLE
Crashes with many subfolders

### ISSUE THREAD

**Issue by mstonermd** [MobiusSync/MobiusSync#1] opened 2020-11-28 18:16 UTC
6.6 GB into a 30 GB folder sync. Have tried ignoring permissions, changing file pull order and deleting and restarting from the beginning. Is there a log file I can send from the iOS analytics?

**Comment by sjpickup** [comment] 2020-11-28 21:27
Hi there, thanks for your report. I have successfully synced a folder of 25.9GB and 229 files. How many files are in your folder, and how many successfully sync before it crashes?

What is the OS of the other device?

If you have "Share with App Developers" enabled in Settings/Privacy/Analytics & Improvements, we should receive a crash report within a few days; otherwise you can find them under "Analytics Data" and copy/paste in here.

**Comment by mstonermd** [comment] 2020-11-28 22:06
Thanks for the quick reply. I found that disabling the filewatcher resolved the issue.  

/MCS

**Comment by sjpickup** [comment] 2020-12-06 18:05
The issue is that syncthing opens an fd for each subfolder being monitored; iOS 14.1 seems to have a max of 4096 but iOS app crashes strangely when approaching this limit. A check for exceeding 4000 has been added, at which point file watcher errors will be displayed.

Upon the realisation that watching for realtime updates isn't very useful under iOS since Syncthing doesn't run continuously, the file watcher has been disabled by default in new folders.

**Comment by mstonermd** [comment] 2020-12-06 19:17
That makes sense. Great app thank you for working on it

/MCS

**Comment by sjpickup** [comment] 2020-12-07 06:20
Fix now released in v1.1. Existing users may wish to manually disable filewatcher on each of their shared folders for performance and to avoid problems if/when their usage grows to total ~4000 subfolders.

**Closed by sjpickup** 2020-12-07 06:20 UTC
Labels: bug

**Comment by mstonermd** [comment] 2020-12-20 13:57
I have attached a screenshot. I sync a 30 GB folder without issues. Some minor file additions of now cause the following error. My iOS device has over 70 GB of free space on it still.

Thanks for creating this product. It has been a major change in my efficiency

Mike

**Comment by sjpickup** [comment] 2020-12-21 06:19
> I have attached a screenshot.

Attachments don't come through on email replies to github issues. Can you attach via the web interface?

**Comment by mstonermd** [comment] 2020-12-21 10:45
![900B9542-5231-410C-A775-DC52676BFF9D](https://user-images.githubusercontent.com/22255258/102768753-a7b3fc00-434f-11eb-8c11-53aa3019b00e.png)

**Comment by sjpickup** [comment] 2020-12-22 06:23
Thanks. OK, I suspect I know what is going on. Syncthing is probably technically acting correctly, however there are probably temporary files that could be cleaned up by iOS to make enough space available. I think the iOS storage usage display includes temporary files under free space. I'll split this to a new issue.
