### ISSUE TITLE
name is invalid, must not start with period on iOS.

### ISSUE THREAD

**Issue by dober** [MobiusSync/MobiusSync#26] opened 2021-01-22 21:56 UTC
Hello,

Found a bug (or feature?) with dotfiles folder syncing - name is invalid, must not start with period on iOS.

as i know somehow Secure ShellFish works with dotfiles via Files app, maybe it can help

![photo_2021-01-23_00-49-44](https://user-images.githubusercontent.com/5652940/105552993-d68a0d00-5d15-11eb-980a-986e8178c767.jpg)

**Comment by sjpickup** [comment] 2021-01-23 18:54
This was intended to be a feature because dot files don't appear in the Files app. The files can sync but are basically inaccessible so waste space.

The idea of making it an error was to prompt you to rename the files so they could become visible on iOS, however I now realise this isn't always feasible and could be seen as a bug. I'll do a new release in the next few days to back this out until I consider how to make it configurable.

**Comment by sjpickup** [comment] 2021-01-23 20:23
On further investigation, I see that this acts consistently with how invalid filenames on Windows are handled, so seems justfified to do the same here... unless Secure Shellfish shows us a way around this apparent limitation of the Files ap.

**Comment by sjpickup** [comment] 2021-01-24 05:18
Also mentioned here: https://forum.syncthing.net/t/name-is-invalid-must-not-start-with-period-on-ios-mobius-sync/16230

Note this "feature" has been in Möbius Sync since v1.0.

I will treat this issue as an enhancement request to make it configurable, per folder, whether to alert and skip syncing dotfiles, or whether to sync them (even though they may be inaccessible on iOS, they can be synced elsewhere).

**Comment by cbeams** [comment] 2021-01-30 16:13
This may be a feature for some but is a bug for me. I’m editing synced files with Vim, and Vim’s dot-prefixed swap files are triggering this failure. I don’t care if the swap file is synced or not, but I’d at least like the option to quell this warning. A `.gitignore`-style (`.nosync`?) file could be a nice way to go here.

**Comment by cbeams** [comment] 2021-02-01 14:38
Nevermind, I see now that ignore patters are an existing feature in Syncthing. The following solves my problem (and indeed there is also already a `.stignore` file implemented as suggested above).

<img width="902" alt="image" src="https://user-images.githubusercontent.com/301810/106472874-6a40a380-64a3-11eb-8256-b2b43cf726da.png">

**Comment by kk7ds** [comment] 2021-04-09 16:35
Yep, I just excluded ".*" to squelch this. This probably should be a default setting for this app instead of just requiring everyone to go in and do the same.

**Comment by jtagcat** [comment] 2021-04-20 13:58
Is there a way to disable this feature (per-folder or app-wide toggle (per-folder can be combined folder defaults)?

Already have a dotfolder for critical low-size backups. Since the data can be restored to other devices, and then used.

This would also remove Möbius Sync as a blocker, if/when other apps display dotfiles.

**Comment by ghost** [comment] 2021-05-06 21:50
I think dot-files should be automatically renamed on iOS devices, if they cannot be supported. Or if dot-files can be stored but not shown through Files.app, they should be stored but not shown. Resilio Sync has no problem with them. I currently use ResilioSync to also backup files on my iOS devices; and use my iOS devices as fancy wireless USB sticks to transfer data between computers. It is necessary to be able to store dot-files, for example `.hg` for Mercurial repository metadata (`.git`if you use that awful piece of software). Such files cannot be renamed, and cannot be ignored.

**Comment by artinmg** [comment] 2021-07-16 15:30
I agree that syncing dot files is necessary in some cases. If I want to sync e.g. coding projects of whatever type I may need various configuration files which I don’t need to see on iOS but I will need to sync to e.g. switch between two different machines and continue working on a project. This would make it a true replacement for a cloud syncing service where I can expect to work on the same project on a Mac or PC or what have you as necessary.

**Comment by rasa** [comment] 2021-07-30 15:09
There is a [PR](https://github.com/syncthing/syncthing/pull/7828) to address this issue. It's not enabled by default, but can be enabled in the GUI by selecting Actions > Advanced > Folder > Encoder Filesystem Type > typing in `auto` and then clicking Save.

While this PR fixes these sync failures, it does so by internally renaming the failing files to begin with a safe unicode character (0xf02e), instead of with a period. It still syncs the files using the original name.

**Comment by ghost** [comment] 2021-08-10 11:51
How to use the PR without paying Apple $90/year protection money?  I'm afraid the project is abandoned by the author due to the total lack of responses for several months now.

**Comment by rasa** [comment] 2021-08-12 02:58
> How to use the PR without paying Apple $90/year protection money? 

If this [PR](https://github.com/syncthing/syncthing/pull/7876) is accepted into Syncthing, then it most likely will be in Mobius Sync eventually. 

The author of Mobius Sync has been keeping his [fork](https://github.com/MobiusSync/syncthing/commits/main) of Syncthing updated, so I wouldn't give up hope on it just yet.

**Comment by SimonPickup** [comment] 2021-10-26 18:32
I now consider this to be a bug rather than an feature, as there is a critical difference between this and invalid filenames on Windows. Filenames (and folder names) beginning with a dot are **legal** in iOS, it's just that the Files app doesn't show them.

So I'll include a **fix** to allow them to be synced. If users don't want these **invisible** files to be synced onto iOS, they can always add an ignore patten.

**Comment by rasa** [comment] 2021-10-26 21:55
Agreed. Other file manager apps see leading-dot files just fine.

**Comment by SimonPickup** [comment] 2021-10-31 17:40
> Agreed. Other file manager apps see leading-dot files just fine.

What other file manager apps? Do you mean on iOS?

**Comment by SimonPickup** [comment] 2021-10-31 17:40
Fix is now in TestFlight - build 202110311729.

**Comment by rasa** [comment] 2021-10-31 19:42
> What other file manager apps? Do you mean on iOS?

@sjpickup Yes, iOS apps. I use FE File Explorer, but there are many iOS file manager apps that allow you to see and create filenames with leading periods.

**Comment by SimonPickup** [comment] 2021-11-01 04:59
> > What other file manager apps? Do you mean on iOS?
> 
> @sjpickup Yes, iOS apps. I use FE File Explorer, but there are many iOS file manager apps that allow you to see and create filenames with leading periods.

@rasa, OK I tried FE File Explorerm but it of course cannot see Mobius Sync's files. The problem is NOT iOS's fundamental ability to create and see _dot files_, the problem is the Apple _Files app_ choses to hide them, and that is the only way Mobius Sync's file hierarchy can be viewed (or transferred in/out).

**Closed** 2021-11-01 06:48 UTC
Labels: bug

**Comment by rasa** [comment] 2021-11-01 07:30
> @rasa, OK I tried FE File Explorer but it of course cannot see Mobius Sync's files.

@sjpickup It does see them, but you have to jump thru hoops a bit: 
1. Click the `+` symbol
2. Select `External Location`
3. Select `On My iPad`
4. Select `Mobius Sync`
5. Select `Sync`
6. Click `Done`
7. Under `Connections`, select `Sync`:

![93B33980-EB50-450A-8F4F-8A0009AF6248](https://user-images.githubusercontent.com/220772/139635938-b9cc0720-9405-4431-a7f5-38fcf812dfa3.jpeg)
