### ISSUE TITLE
Application not available in App Store

### ISSUE THREAD

**Issue by lauhub** [MobiusSync/MobiusSync#69] opened 2022-04-24 16:09 UTC
Hi,

I live in France and I would like to use your application. However, it is not possible to download it because it is not available in french store.

Could you do something ?

**Comment by NatHarari** [comment] 2022-05-09 10:30
I literally came here to say the same thing. Could you please make it available in France? Thanks!

**Comment by jcaude** [comment] 2022-05-16 21:05
okay, same here .. that's a shame as it would be a winning replacement for Synology drive that doesn't support offline browsing..

**Comment by NatHarari** [comment] 2022-05-16 21:18
> okay, same here .. that's a shame as it would be a winning replacement for Synology drive that doesn't support offline browsing..

Yeah, I’m surprised there’s no answer at all either, considering it’s not an abandoned project from what I can tell.

**Comment by SimonPickup** [comment] 2022-05-20 16:10
Duplicate of https://github.com/MobiusSync/MobiusSync/issues/27

**Closed as completed by SimonPickup** 2022-05-20 16:10 UTC
Labels: duplicate
