### ISSUE TITLE
out of sync issue after deleting files

### ISSUE THREAD

**Issue by thob** [MobiusSync/MobiusSync#195] opened 2024-08-17 14:35 UTC
I stumbled upon an issue with deleted images. I got now 10 out of sync items with 0B. I ran `--reset-deltas` on the recipient this did not remedy the issue. Is this something I should rather do on iOS, if so how?

Thanks

**Comment by SimonPickup** [comment] 2024-08-17 19:39
Seems to be a duplicate of #173

**Closed as completed by SimonPickup** 2024-08-17 19:39 UTC
Labels: duplicate
