### ISSUE TITLE
Stops sync on iOS 18.0.1

### ISSUE THREAD

**Issue by laatzener** [MobiusSync/MobiusSync#206] opened 2024-10-19 21:04 UTC
Have the Pro version since 2 days. It works some hours, but then it stops sync in background on my iPhone 14 . When I open the App, it flickers like GUI Elements are added and removed fastly. Only killing the App helps, then the flickering is ended and syncing works again.
On the iPhone of my wife same happens.
On my Raspi Syncthing 1.28.0 is Running.

**Comment by SimonPickup** [comment] 2024-10-20 15:07
This is probably caused by #177 or #193, which is fixed in TestFlight. Feel free to confirm for yourself before the public release. See #194.

**Closed as completed by SimonPickup** 2024-10-20 15:07 UTC
Labels: duplicate
