### ISSUE TITLE
insufficient space on disk for database

### ISSUE THREAD

**Issue by jakajancar** [MobiusSync/MobiusSync#53] opened 2021-09-07 21:22 UTC
Fresh install, plenty of space, 0 synced files, 0 peers. Tried recreating the folder, same. iOS 14.7.1.
```
2021-09-07 17:19:54: Error on folder vfy9t-ceve3 at vfy9t-ceve3: insufficient space on disk for database (/private/var/mobile/Containers/Data/Application/2334FB31-8A88-41C7-9896-19E7FCB05318/Library/Application Support/Syncthing/index-v0.14.0.db): 0.8 % < 1 %
```
Maybe iOS just does not report free space correctly?

**Comment by rasa** [comment] 2021-09-08 00:50
The `0.8 % < 1 %` at the end suggests you can address this issue in the MobiusSync app by:
1. Clicking [Actions] in the upper right,
2. Clicking [Settings],
3. Entering in a value in the "Minimum Free Disk Space" field of `0.7` or less. Even `0` works.
4. Clicking [Save].

For that to take effect, you may then need to restart the app, or the iPad. On my iPad, I swipe up on the app in the App Switcher to kill the app. 

BTW, I've been using MobiusSync for months now, with lots of space, and never encountered this issue.

**Comment by jakajancar** [comment] 2021-09-08 00:57
"Works on my machine", in other words? ;)

Setting it to 0 works for me too, so not a big deal. But I have way more space available than that. It's spurious. So just reporting it.

**Comment by rasa** [comment] 2021-09-09 22:32
> "Works on my machine", in other words? ;)

Yeah, sorry. Perhaps it’s iOS version specific.

**Comment by SimonPickup** [comment] 2021-10-26 18:39
Closing as a duplicate of #17. Please reopen and add more detail explain why this is different, if you believe it to be.

**Closed as completed by SimonPickup** 2021-10-26 18:39 UTC
Labels: duplicate
