### ISSUE TITLE
Can’t sync custom folders

### ISSUE THREAD

**Issue by Radoslaw7** [MobiusSync/MobiusSync#203] opened 2024-10-13 16:22 UTC
Hello.
My device: iPad Pro 4th gen
MobiusSync App’s version is the newest. Installed it and bought extended features today (13.10.2024).

While I am trying to add a folder with external path to folder made by me, there is an error that says „Unsupported folder”.
I guess there is no option to sync custom-made folders, outside of these belonging to certain apps.

Is there a possibility for you to implement that function, or is it matter of iOS/iPadOS’ approach to, I guess protecting user’s files?

https://github.com/user-attachments/assets/1efdcebd-425a-4e57-949d-2361f66464f6

**Comment by SimonPickup** [comment] 2024-10-13 17:05
This is a duplicate of #197 which has just been made available to TestFlight users and will be released soon.

**Closed as completed by SimonPickup** 2024-10-13 17:05 UTC
Labels: duplicate
